apiVersion: v1
kind: Pod
metadata:
  name: image-pull-demo-pod
  labels:
    app: troubleshooting
spec:
  containers:
  - name: app-container-demo
    #old error code -Imagepullbackoff
    #image: nginx:this-tag-does-not-exist-999
    #New fixed code -stable Version given
    image: nginx:1.30.5
    imagePullPolicy: Always